services:
  api:
    build: .
    environment:
      - API_MONGO_URI=localhost:27017
      - FLASK_ENV=production
      - FLASK_APP=api.py
    depends_on:
      - db
    volumes:
      - .:/code
    restart: on-failure:5

  db:
    image: mongo:3.4-jessie
    volumes:
      - /srv/prato_aberto/data_mongo:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    name: pratoaberto
    external: true